spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hospital?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

server:
  servlet:
    jsp:
      init-parameters:
        development: true

mybatis:
  mapper-locations: classpath:com/xmu/mapper/xml/*.xml
  type-aliases-package: com.xmu.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl