package com.xmu.hospital.mapper;

import com.xmu.hospital.entity.Hospital;
import com.xmu.hospital.entity.HospitalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HospitalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    long countByExample(HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    int deleteByExample(HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    int deleteByPrimaryKey(Long hId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    int insert(Hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    int insertSelective(Hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    List<Hospital> selectByExample(HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    Hospital selectByPrimaryKey(Long hId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") Hospital record, @Param("example") HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    int updateByExample(@Param("record") Hospital record, @Param("example") HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    int updateByPrimaryKeySelective(Hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    int updateByPrimaryKey(Hospital record);
}