package com.xmu.entity;

public class Hospital {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.h_id
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private Long hId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.h_account
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private String hAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.h_password
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private String hPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.h_name
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private String hName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.h_id
     *
     * @return the value of hospital.h_id
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public Long gethId() {
        return hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.h_id
     *
     * @param hId the value for hospital.h_id
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void sethId(Long hId) {
        this.hId = hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.h_account
     *
     * @return the value of hospital.h_account
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public String gethAccount() {
        return hAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.h_account
     *
     * @param hAccount the value for hospital.h_account
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void sethAccount(String hAccount) {
        this.hAccount = hAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.h_password
     *
     * @return the value of hospital.h_password
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public String gethPassword() {
        return hPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.h_password
     *
     * @param hPassword the value for hospital.h_password
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void sethPassword(String hPassword) {
        this.hPassword = hPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.h_name
     *
     * @return the value of hospital.h_name
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public String gethName() {
        return hName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.h_name
     *
     * @param hName the value for hospital.h_name
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void sethName(String hName) {
        this.hName = hName;
    }
}