package com.xmu.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_id
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private Long oId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_did
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private Long oDid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_hid
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private Long oHid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_userid
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private Long oUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_raddress
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private String oRaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_status
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private Byte oStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_date
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private Date oDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_price
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private BigDecimal oPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_id
     *
     * @return the value of orders.o_id
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public Long getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_id
     *
     * @param oId the value for orders.o_id
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void setoId(Long oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_did
     *
     * @return the value of orders.o_did
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public Long getoDid() {
        return oDid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_did
     *
     * @param oDid the value for orders.o_did
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void setoDid(Long oDid) {
        this.oDid = oDid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_hid
     *
     * @return the value of orders.o_hid
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public Long getoHid() {
        return oHid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_hid
     *
     * @param oHid the value for orders.o_hid
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void setoHid(Long oHid) {
        this.oHid = oHid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_userid
     *
     * @return the value of orders.o_userid
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public Long getoUserid() {
        return oUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_userid
     *
     * @param oUserid the value for orders.o_userid
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void setoUserid(Long oUserid) {
        this.oUserid = oUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_raddress
     *
     * @return the value of orders.o_raddress
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public String getoRaddress() {
        return oRaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_raddress
     *
     * @param oRaddress the value for orders.o_raddress
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void setoRaddress(String oRaddress) {
        this.oRaddress = oRaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_status
     *
     * @return the value of orders.o_status
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public Byte getoStatus() {
        return oStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_status
     *
     * @param oStatus the value for orders.o_status
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void setoStatus(Byte oStatus) {
        this.oStatus = oStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_date
     *
     * @return the value of orders.o_date
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public Date getoDate() {
        return oDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_date
     *
     * @param oDate the value for orders.o_date
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void setoDate(Date oDate) {
        this.oDate = oDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_price
     *
     * @return the value of orders.o_price
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public BigDecimal getoPrice() {
        return oPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_price
     *
     * @param oPrice the value for orders.o_price
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void setoPrice(BigDecimal oPrice) {
        this.oPrice = oPrice;
    }
}