package com.xmu.entity;

public class Room {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.r_id
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private Long rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.r_address
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private String rAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.r_desc
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private String rDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.r_max
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private Byte rMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.r_num
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private Byte rNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.r_hid
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private Long rHid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.r_id
     *
     * @return the value of room.r_id
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public Long getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.r_id
     *
     * @param rId the value for room.r_id
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void setrId(Long rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.r_address
     *
     * @return the value of room.r_address
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public String getrAddress() {
        return rAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.r_address
     *
     * @param rAddress the value for room.r_address
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void setrAddress(String rAddress) {
        this.rAddress = rAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.r_desc
     *
     * @return the value of room.r_desc
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public String getrDesc() {
        return rDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.r_desc
     *
     * @param rDesc the value for room.r_desc
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void setrDesc(String rDesc) {
        this.rDesc = rDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.r_max
     *
     * @return the value of room.r_max
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public Byte getrMax() {
        return rMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.r_max
     *
     * @param rMax the value for room.r_max
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void setrMax(Byte rMax) {
        this.rMax = rMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.r_num
     *
     * @return the value of room.r_num
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public Byte getrNum() {
        return rNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.r_num
     *
     * @param rNum the value for room.r_num
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void setrNum(Byte rNum) {
        this.rNum = rNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.r_hid
     *
     * @return the value of room.r_hid
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public Long getrHid() {
        return rHid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.r_hid
     *
     * @param rHid the value for room.r_hid
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void setrHid(Long rHid) {
        this.rHid = rHid;
    }
}