package com.xmu.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_id
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private Long uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_account
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private String uAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_password
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private String uPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_name
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private String uName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_age
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private Byte uAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_sex
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private Boolean uSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_phone
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    private String uPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_id
     *
     * @return the value of user.u_id
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_id
     *
     * @param uId the value for user.u_id
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_account
     *
     * @return the value of user.u_account
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public String getuAccount() {
        return uAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_account
     *
     * @param uAccount the value for user.u_account
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void setuAccount(String uAccount) {
        this.uAccount = uAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_password
     *
     * @return the value of user.u_password
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public String getuPassword() {
        return uPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_password
     *
     * @param uPassword the value for user.u_password
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void setuPassword(String uPassword) {
        this.uPassword = uPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_name
     *
     * @return the value of user.u_name
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_name
     *
     * @param uName the value for user.u_name
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void setuName(String uName) {
        this.uName = uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_age
     *
     * @return the value of user.u_age
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public Byte getuAge() {
        return uAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_age
     *
     * @param uAge the value for user.u_age
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void setuAge(Byte uAge) {
        this.uAge = uAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_sex
     *
     * @return the value of user.u_sex
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public Boolean getuSex() {
        return uSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_sex
     *
     * @param uSex the value for user.u_sex
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void setuSex(Boolean uSex) {
        this.uSex = uSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_phone
     *
     * @return the value of user.u_phone
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public String getuPhone() {
        return uPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_phone
     *
     * @param uPhone the value for user.u_phone
     *
     * @mbggenerated Fri Jul 10 15:53:47 CST 2020
     */
    public void setuPhone(String uPhone) {
        this.uPhone = uPhone;
    }
}