package com.xmu.hospital.entity;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_id
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    private Long aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_account
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    private String aAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_password
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    private String aPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_id
     *
     * @return the value of admin.a_id
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    public Long getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_id
     *
     * @param aId the value for admin.a_id
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    public void setaId(Long aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_account
     *
     * @return the value of admin.a_account
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    public String getaAccount() {
        return aAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_account
     *
     * @param aAccount the value for admin.a_account
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    public void setaAccount(String aAccount) {
        this.aAccount = aAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_password
     *
     * @return the value of admin.a_password
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    public String getaPassword() {
        return aPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_password
     *
     * @param aPassword the value for admin.a_password
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    public void setaPassword(String aPassword) {
        this.aPassword = aPassword;
    }
}