package com.xmu.hospital.entity;

public class Doctor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.d_id
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    private Long dId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.d_name
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    private String dName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.d_type
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    private String dType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.d_desc
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    private String dDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.d_phone
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    private String dPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.d_rid
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    private Long dRid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.d_hid
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    private Long dHid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.d_id
     *
     * @return the value of doctor.d_id
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    public Long getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.d_id
     *
     * @param dId the value for doctor.d_id
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    public void setdId(Long dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.d_name
     *
     * @return the value of doctor.d_name
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.d_name
     *
     * @param dName the value for doctor.d_name
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    public void setdName(String dName) {
        this.dName = dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.d_type
     *
     * @return the value of doctor.d_type
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    public String getdType() {
        return dType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.d_type
     *
     * @param dType the value for doctor.d_type
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    public void setdType(String dType) {
        this.dType = dType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.d_desc
     *
     * @return the value of doctor.d_desc
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    public String getdDesc() {
        return dDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.d_desc
     *
     * @param dDesc the value for doctor.d_desc
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    public void setdDesc(String dDesc) {
        this.dDesc = dDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.d_phone
     *
     * @return the value of doctor.d_phone
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    public String getdPhone() {
        return dPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.d_phone
     *
     * @param dPhone the value for doctor.d_phone
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    public void setdPhone(String dPhone) {
        this.dPhone = dPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.d_rid
     *
     * @return the value of doctor.d_rid
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    public Long getdRid() {
        return dRid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.d_rid
     *
     * @param dRid the value for doctor.d_rid
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    public void setdRid(Long dRid) {
        this.dRid = dRid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.d_hid
     *
     * @return the value of doctor.d_hid
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    public Long getdHid() {
        return dHid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.d_hid
     *
     * @param dHid the value for doctor.d_hid
     *
     * @mbg.generated Fri Jul 10 10:17:58 CST 2020
     */
    public void setdHid(Long dHid) {
        this.dHid = dHid;
    }
}